/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadOfertaRouteImport } from './routes/upload-oferta'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RezultatGratuitRouteImport } from './routes/rezultat-gratuit'
import { Route as RecomandareSistemRouteImport } from './routes/recomandare-sistem'
import { Route as RaportCompletRouteImport } from './routes/raport-complet'
import { Route as IntroducereManualaRouteImport } from './routes/introducere-manuala'
import { Route as IntrebariFrecventeRouteImport } from './routes/intrebari-frecvente'
import { Route as HartaSolaraRomaniaRouteImport } from './routes/harta-solara-romania'
import { Route as ExempluRaportRouteImport } from './routes/exemplu-raport'
import { Route as CumFunctioneazaRouteImport } from './routes/cum-functioneaza'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ContRouteImport } from './routes/cont'
import { Route as AutentificareRouteImport } from './routes/autentificare'
import { Route as AnalizaRouteImport } from './routes/analiza'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RezultatGratuitAnalysisIdRouteImport } from './routes/rezultat-gratuit.$analysisId'
import { Route as RaportCompletAnalysisIdRouteImport } from './routes/raport-complet.$analysisId'
import { Route as LegalTermeniRouteImport } from './routes/legal.termeni'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as LegalConfidentialitateRouteImport } from './routes/legal.confidentialitate'
import { Route as CorectareOfferIdRouteImport } from './routes/corectare.$offerId'
import { Route as ContSetariRouteImport } from './routes/cont.setari'
import { Route as ContRapoarteRouteImport } from './routes/cont.rapoarte'
import { Route as ApiAnalyticsRouteImport } from './routes/api/analytics'
import { Route as AnalizaOfferIdRouteImport } from './routes/analiza.$offerId'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as AuthenticatedAdminWebhooksRouteImport } from './routes/_authenticated/admin.webhooks'
import { Route as AuthenticatedAdminSetariRouteImport } from './routes/_authenticated/admin.setari'
import { Route as AuthenticatedAdminPlatiRouteImport } from './routes/_authenticated/admin.plati'
import { Route as AuthenticatedAdminPiataRouteImport } from './routes/_authenticated/admin.piata'
import { Route as AuthenticatedAdminOferteRouteImport } from './routes/_authenticated/admin.oferte'
import { Route as AuthenticatedAdminMesajeRouteImport } from './routes/_authenticated/admin.mesaje'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'

const UploadOfertaRoute = UploadOfertaRouteImport.update({
  id: '/upload-oferta',
  path: '/upload-oferta',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RezultatGratuitRoute = RezultatGratuitRouteImport.update({
  id: '/rezultat-gratuit',
  path: '/rezultat-gratuit',
  getParentRoute: () => rootRouteImport,
} as any)
const RecomandareSistemRoute = RecomandareSistemRouteImport.update({
  id: '/recomandare-sistem',
  path: '/recomandare-sistem',
  getParentRoute: () => rootRouteImport,
} as any)
const RaportCompletRoute = RaportCompletRouteImport.update({
  id: '/raport-complet',
  path: '/raport-complet',
  getParentRoute: () => rootRouteImport,
} as any)
const IntroducereManualaRoute = IntroducereManualaRouteImport.update({
  id: '/introducere-manuala',
  path: '/introducere-manuala',
  getParentRoute: () => rootRouteImport,
} as any)
const IntrebariFrecventeRoute = IntrebariFrecventeRouteImport.update({
  id: '/intrebari-frecvente',
  path: '/intrebari-frecvente',
  getParentRoute: () => rootRouteImport,
} as any)
const HartaSolaraRomaniaRoute = HartaSolaraRomaniaRouteImport.update({
  id: '/harta-solara-romania',
  path: '/harta-solara-romania',
  getParentRoute: () => rootRouteImport,
} as any)
const ExempluRaportRoute = ExempluRaportRouteImport.update({
  id: '/exemplu-raport',
  path: '/exemplu-raport',
  getParentRoute: () => rootRouteImport,
} as any)
const CumFunctioneazaRoute = CumFunctioneazaRouteImport.update({
  id: '/cum-functioneaza',
  path: '/cum-functioneaza',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ContRoute = ContRouteImport.update({
  id: '/cont',
  path: '/cont',
  getParentRoute: () => rootRouteImport,
} as any)
const AutentificareRoute = AutentificareRouteImport.update({
  id: '/autentificare',
  path: '/autentificare',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalizaRoute = AnalizaRouteImport.update({
  id: '/analiza',
  path: '/analiza',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RezultatGratuitAnalysisIdRoute =
  RezultatGratuitAnalysisIdRouteImport.update({
    id: '/$analysisId',
    path: '/$analysisId',
    getParentRoute: () => RezultatGratuitRoute,
  } as any)
const RaportCompletAnalysisIdRoute = RaportCompletAnalysisIdRouteImport.update({
  id: '/$analysisId',
  path: '/$analysisId',
  getParentRoute: () => RaportCompletRoute,
} as any)
const LegalTermeniRoute = LegalTermeniRouteImport.update({
  id: '/legal/termeni',
  path: '/legal/termeni',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalConfidentialitateRoute = LegalConfidentialitateRouteImport.update({
  id: '/legal/confidentialitate',
  path: '/legal/confidentialitate',
  getParentRoute: () => rootRouteImport,
} as any)
const CorectareOfferIdRoute = CorectareOfferIdRouteImport.update({
  id: '/corectare/$offerId',
  path: '/corectare/$offerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ContSetariRoute = ContSetariRouteImport.update({
  id: '/setari',
  path: '/setari',
  getParentRoute: () => ContRoute,
} as any)
const ContRapoarteRoute = ContRapoarteRouteImport.update({
  id: '/rapoarte',
  path: '/rapoarte',
  getParentRoute: () => ContRoute,
} as any)
const ApiAnalyticsRoute = ApiAnalyticsRouteImport.update({
  id: '/api/analytics',
  path: '/api/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalizaOfferIdRoute = AnalizaOfferIdRouteImport.update({
  id: '/$offerId',
  path: '/$offerId',
  getParentRoute: () => AnalizaRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminWebhooksRoute =
  AuthenticatedAdminWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSetariRoute =
  AuthenticatedAdminSetariRouteImport.update({
    id: '/setari',
    path: '/setari',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPlatiRoute = AuthenticatedAdminPlatiRouteImport.update({
  id: '/plati',
  path: '/plati',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPiataRoute = AuthenticatedAdminPiataRouteImport.update({
  id: '/piata',
  path: '/piata',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminOferteRoute =
  AuthenticatedAdminOferteRouteImport.update({
    id: '/oferte',
    path: '/oferte',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMesajeRoute =
  AuthenticatedAdminMesajeRouteImport.update({
    id: '/mesaje',
    path: '/mesaje',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analiza': typeof AnalizaRouteWithChildren
  '/autentificare': typeof AutentificareRoute
  '/cont': typeof ContRouteWithChildren
  '/contact': typeof ContactRoute
  '/cum-functioneaza': typeof CumFunctioneazaRoute
  '/exemplu-raport': typeof ExempluRaportRoute
  '/harta-solara-romania': typeof HartaSolaraRomaniaRoute
  '/intrebari-frecvente': typeof IntrebariFrecventeRoute
  '/introducere-manuala': typeof IntroducereManualaRoute
  '/raport-complet': typeof RaportCompletRouteWithChildren
  '/recomandare-sistem': typeof RecomandareSistemRoute
  '/rezultat-gratuit': typeof RezultatGratuitRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/upload-oferta': typeof UploadOfertaRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/analiza/$offerId': typeof AnalizaOfferIdRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/cont/rapoarte': typeof ContRapoarteRoute
  '/cont/setari': typeof ContSetariRoute
  '/corectare/$offerId': typeof CorectareOfferIdRoute
  '/legal/confidentialitate': typeof LegalConfidentialitateRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/termeni': typeof LegalTermeniRoute
  '/raport-complet/$analysisId': typeof RaportCompletAnalysisIdRoute
  '/rezultat-gratuit/$analysisId': typeof RezultatGratuitAnalysisIdRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/mesaje': typeof AuthenticatedAdminMesajeRoute
  '/admin/oferte': typeof AuthenticatedAdminOferteRoute
  '/admin/piata': typeof AuthenticatedAdminPiataRoute
  '/admin/plati': typeof AuthenticatedAdminPlatiRoute
  '/admin/setari': typeof AuthenticatedAdminSetariRoute
  '/admin/webhooks': typeof AuthenticatedAdminWebhooksRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analiza': typeof AnalizaRouteWithChildren
  '/autentificare': typeof AutentificareRoute
  '/cont': typeof ContRouteWithChildren
  '/contact': typeof ContactRoute
  '/cum-functioneaza': typeof CumFunctioneazaRoute
  '/exemplu-raport': typeof ExempluRaportRoute
  '/harta-solara-romania': typeof HartaSolaraRomaniaRoute
  '/intrebari-frecvente': typeof IntrebariFrecventeRoute
  '/introducere-manuala': typeof IntroducereManualaRoute
  '/raport-complet': typeof RaportCompletRouteWithChildren
  '/recomandare-sistem': typeof RecomandareSistemRoute
  '/rezultat-gratuit': typeof RezultatGratuitRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/upload-oferta': typeof UploadOfertaRoute
  '/analiza/$offerId': typeof AnalizaOfferIdRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/cont/rapoarte': typeof ContRapoarteRoute
  '/cont/setari': typeof ContSetariRoute
  '/corectare/$offerId': typeof CorectareOfferIdRoute
  '/legal/confidentialitate': typeof LegalConfidentialitateRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/termeni': typeof LegalTermeniRoute
  '/raport-complet/$analysisId': typeof RaportCompletAnalysisIdRoute
  '/rezultat-gratuit/$analysisId': typeof RezultatGratuitAnalysisIdRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/mesaje': typeof AuthenticatedAdminMesajeRoute
  '/admin/oferte': typeof AuthenticatedAdminOferteRoute
  '/admin/piata': typeof AuthenticatedAdminPiataRoute
  '/admin/plati': typeof AuthenticatedAdminPlatiRoute
  '/admin/setari': typeof AuthenticatedAdminSetariRoute
  '/admin/webhooks': typeof AuthenticatedAdminWebhooksRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/analiza': typeof AnalizaRouteWithChildren
  '/autentificare': typeof AutentificareRoute
  '/cont': typeof ContRouteWithChildren
  '/contact': typeof ContactRoute
  '/cum-functioneaza': typeof CumFunctioneazaRoute
  '/exemplu-raport': typeof ExempluRaportRoute
  '/harta-solara-romania': typeof HartaSolaraRomaniaRoute
  '/intrebari-frecvente': typeof IntrebariFrecventeRoute
  '/introducere-manuala': typeof IntroducereManualaRoute
  '/raport-complet': typeof RaportCompletRouteWithChildren
  '/recomandare-sistem': typeof RecomandareSistemRoute
  '/rezultat-gratuit': typeof RezultatGratuitRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/upload-oferta': typeof UploadOfertaRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/analiza/$offerId': typeof AnalizaOfferIdRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/cont/rapoarte': typeof ContRapoarteRoute
  '/cont/setari': typeof ContSetariRoute
  '/corectare/$offerId': typeof CorectareOfferIdRoute
  '/legal/confidentialitate': typeof LegalConfidentialitateRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/termeni': typeof LegalTermeniRoute
  '/raport-complet/$analysisId': typeof RaportCompletAnalysisIdRoute
  '/rezultat-gratuit/$analysisId': typeof RezultatGratuitAnalysisIdRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/mesaje': typeof AuthenticatedAdminMesajeRoute
  '/_authenticated/admin/oferte': typeof AuthenticatedAdminOferteRoute
  '/_authenticated/admin/piata': typeof AuthenticatedAdminPiataRoute
  '/_authenticated/admin/plati': typeof AuthenticatedAdminPlatiRoute
  '/_authenticated/admin/setari': typeof AuthenticatedAdminSetariRoute
  '/_authenticated/admin/webhooks': typeof AuthenticatedAdminWebhooksRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analiza'
    | '/autentificare'
    | '/cont'
    | '/contact'
    | '/cum-functioneaza'
    | '/exemplu-raport'
    | '/harta-solara-romania'
    | '/intrebari-frecvente'
    | '/introducere-manuala'
    | '/raport-complet'
    | '/recomandare-sistem'
    | '/rezultat-gratuit'
    | '/sitemap.xml'
    | '/upload-oferta'
    | '/admin'
    | '/analiza/$offerId'
    | '/api/analytics'
    | '/cont/rapoarte'
    | '/cont/setari'
    | '/corectare/$offerId'
    | '/legal/confidentialitate'
    | '/legal/cookies'
    | '/legal/termeni'
    | '/raport-complet/$analysisId'
    | '/rezultat-gratuit/$analysisId'
    | '/admin/audit'
    | '/admin/mesaje'
    | '/admin/oferte'
    | '/admin/piata'
    | '/admin/plati'
    | '/admin/setari'
    | '/admin/webhooks'
    | '/api/public/stripe-webhook'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analiza'
    | '/autentificare'
    | '/cont'
    | '/contact'
    | '/cum-functioneaza'
    | '/exemplu-raport'
    | '/harta-solara-romania'
    | '/intrebari-frecvente'
    | '/introducere-manuala'
    | '/raport-complet'
    | '/recomandare-sistem'
    | '/rezultat-gratuit'
    | '/sitemap.xml'
    | '/upload-oferta'
    | '/analiza/$offerId'
    | '/api/analytics'
    | '/cont/rapoarte'
    | '/cont/setari'
    | '/corectare/$offerId'
    | '/legal/confidentialitate'
    | '/legal/cookies'
    | '/legal/termeni'
    | '/raport-complet/$analysisId'
    | '/rezultat-gratuit/$analysisId'
    | '/admin/audit'
    | '/admin/mesaje'
    | '/admin/oferte'
    | '/admin/piata'
    | '/admin/plati'
    | '/admin/setari'
    | '/admin/webhooks'
    | '/api/public/stripe-webhook'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/analiza'
    | '/autentificare'
    | '/cont'
    | '/contact'
    | '/cum-functioneaza'
    | '/exemplu-raport'
    | '/harta-solara-romania'
    | '/intrebari-frecvente'
    | '/introducere-manuala'
    | '/raport-complet'
    | '/recomandare-sistem'
    | '/rezultat-gratuit'
    | '/sitemap.xml'
    | '/upload-oferta'
    | '/_authenticated/admin'
    | '/analiza/$offerId'
    | '/api/analytics'
    | '/cont/rapoarte'
    | '/cont/setari'
    | '/corectare/$offerId'
    | '/legal/confidentialitate'
    | '/legal/cookies'
    | '/legal/termeni'
    | '/raport-complet/$analysisId'
    | '/rezultat-gratuit/$analysisId'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/mesaje'
    | '/_authenticated/admin/oferte'
    | '/_authenticated/admin/piata'
    | '/_authenticated/admin/plati'
    | '/_authenticated/admin/setari'
    | '/_authenticated/admin/webhooks'
    | '/api/public/stripe-webhook'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AnalizaRoute: typeof AnalizaRouteWithChildren
  AutentificareRoute: typeof AutentificareRoute
  ContRoute: typeof ContRouteWithChildren
  ContactRoute: typeof ContactRoute
  CumFunctioneazaRoute: typeof CumFunctioneazaRoute
  ExempluRaportRoute: typeof ExempluRaportRoute
  HartaSolaraRomaniaRoute: typeof HartaSolaraRomaniaRoute
  IntrebariFrecventeRoute: typeof IntrebariFrecventeRoute
  IntroducereManualaRoute: typeof IntroducereManualaRoute
  RaportCompletRoute: typeof RaportCompletRouteWithChildren
  RecomandareSistemRoute: typeof RecomandareSistemRoute
  RezultatGratuitRoute: typeof RezultatGratuitRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UploadOfertaRoute: typeof UploadOfertaRoute
  ApiAnalyticsRoute: typeof ApiAnalyticsRoute
  CorectareOfferIdRoute: typeof CorectareOfferIdRoute
  LegalConfidentialitateRoute: typeof LegalConfidentialitateRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalTermeniRoute: typeof LegalTermeniRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload-oferta': {
      id: '/upload-oferta'
      path: '/upload-oferta'
      fullPath: '/upload-oferta'
      preLoaderRoute: typeof UploadOfertaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rezultat-gratuit': {
      id: '/rezultat-gratuit'
      path: '/rezultat-gratuit'
      fullPath: '/rezultat-gratuit'
      preLoaderRoute: typeof RezultatGratuitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recomandare-sistem': {
      id: '/recomandare-sistem'
      path: '/recomandare-sistem'
      fullPath: '/recomandare-sistem'
      preLoaderRoute: typeof RecomandareSistemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raport-complet': {
      id: '/raport-complet'
      path: '/raport-complet'
      fullPath: '/raport-complet'
      preLoaderRoute: typeof RaportCompletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/introducere-manuala': {
      id: '/introducere-manuala'
      path: '/introducere-manuala'
      fullPath: '/introducere-manuala'
      preLoaderRoute: typeof IntroducereManualaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intrebari-frecvente': {
      id: '/intrebari-frecvente'
      path: '/intrebari-frecvente'
      fullPath: '/intrebari-frecvente'
      preLoaderRoute: typeof IntrebariFrecventeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harta-solara-romania': {
      id: '/harta-solara-romania'
      path: '/harta-solara-romania'
      fullPath: '/harta-solara-romania'
      preLoaderRoute: typeof HartaSolaraRomaniaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exemplu-raport': {
      id: '/exemplu-raport'
      path: '/exemplu-raport'
      fullPath: '/exemplu-raport'
      preLoaderRoute: typeof ExempluRaportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cum-functioneaza': {
      id: '/cum-functioneaza'
      path: '/cum-functioneaza'
      fullPath: '/cum-functioneaza'
      preLoaderRoute: typeof CumFunctioneazaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cont': {
      id: '/cont'
      path: '/cont'
      fullPath: '/cont'
      preLoaderRoute: typeof ContRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/autentificare': {
      id: '/autentificare'
      path: '/autentificare'
      fullPath: '/autentificare'
      preLoaderRoute: typeof AutentificareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analiza': {
      id: '/analiza'
      path: '/analiza'
      fullPath: '/analiza'
      preLoaderRoute: typeof AnalizaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rezultat-gratuit/$analysisId': {
      id: '/rezultat-gratuit/$analysisId'
      path: '/$analysisId'
      fullPath: '/rezultat-gratuit/$analysisId'
      preLoaderRoute: typeof RezultatGratuitAnalysisIdRouteImport
      parentRoute: typeof RezultatGratuitRoute
    }
    '/raport-complet/$analysisId': {
      id: '/raport-complet/$analysisId'
      path: '/$analysisId'
      fullPath: '/raport-complet/$analysisId'
      preLoaderRoute: typeof RaportCompletAnalysisIdRouteImport
      parentRoute: typeof RaportCompletRoute
    }
    '/legal/termeni': {
      id: '/legal/termeni'
      path: '/legal/termeni'
      fullPath: '/legal/termeni'
      preLoaderRoute: typeof LegalTermeniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/confidentialitate': {
      id: '/legal/confidentialitate'
      path: '/legal/confidentialitate'
      fullPath: '/legal/confidentialitate'
      preLoaderRoute: typeof LegalConfidentialitateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corectare/$offerId': {
      id: '/corectare/$offerId'
      path: '/corectare/$offerId'
      fullPath: '/corectare/$offerId'
      preLoaderRoute: typeof CorectareOfferIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cont/setari': {
      id: '/cont/setari'
      path: '/setari'
      fullPath: '/cont/setari'
      preLoaderRoute: typeof ContSetariRouteImport
      parentRoute: typeof ContRoute
    }
    '/cont/rapoarte': {
      id: '/cont/rapoarte'
      path: '/rapoarte'
      fullPath: '/cont/rapoarte'
      preLoaderRoute: typeof ContRapoarteRouteImport
      parentRoute: typeof ContRoute
    }
    '/api/analytics': {
      id: '/api/analytics'
      path: '/api/analytics'
      fullPath: '/api/analytics'
      preLoaderRoute: typeof ApiAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analiza/$offerId': {
      id: '/analiza/$offerId'
      path: '/$offerId'
      fullPath: '/analiza/$offerId'
      preLoaderRoute: typeof AnalizaOfferIdRouteImport
      parentRoute: typeof AnalizaRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/webhooks': {
      id: '/_authenticated/admin/webhooks'
      path: '/webhooks'
      fullPath: '/admin/webhooks'
      preLoaderRoute: typeof AuthenticatedAdminWebhooksRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/setari': {
      id: '/_authenticated/admin/setari'
      path: '/setari'
      fullPath: '/admin/setari'
      preLoaderRoute: typeof AuthenticatedAdminSetariRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/plati': {
      id: '/_authenticated/admin/plati'
      path: '/plati'
      fullPath: '/admin/plati'
      preLoaderRoute: typeof AuthenticatedAdminPlatiRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/piata': {
      id: '/_authenticated/admin/piata'
      path: '/piata'
      fullPath: '/admin/piata'
      preLoaderRoute: typeof AuthenticatedAdminPiataRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/oferte': {
      id: '/_authenticated/admin/oferte'
      path: '/oferte'
      fullPath: '/admin/oferte'
      preLoaderRoute: typeof AuthenticatedAdminOferteRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/mesaje': {
      id: '/_authenticated/admin/mesaje'
      path: '/mesaje'
      fullPath: '/admin/mesaje'
      preLoaderRoute: typeof AuthenticatedAdminMesajeRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminMesajeRoute: typeof AuthenticatedAdminMesajeRoute
  AuthenticatedAdminOferteRoute: typeof AuthenticatedAdminOferteRoute
  AuthenticatedAdminPiataRoute: typeof AuthenticatedAdminPiataRoute
  AuthenticatedAdminPlatiRoute: typeof AuthenticatedAdminPlatiRoute
  AuthenticatedAdminSetariRoute: typeof AuthenticatedAdminSetariRoute
  AuthenticatedAdminWebhooksRoute: typeof AuthenticatedAdminWebhooksRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminMesajeRoute: AuthenticatedAdminMesajeRoute,
  AuthenticatedAdminOferteRoute: AuthenticatedAdminOferteRoute,
  AuthenticatedAdminPiataRoute: AuthenticatedAdminPiataRoute,
  AuthenticatedAdminPlatiRoute: AuthenticatedAdminPlatiRoute,
  AuthenticatedAdminSetariRoute: AuthenticatedAdminSetariRoute,
  AuthenticatedAdminWebhooksRoute: AuthenticatedAdminWebhooksRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AnalizaRouteChildren {
  AnalizaOfferIdRoute: typeof AnalizaOfferIdRoute
}

const AnalizaRouteChildren: AnalizaRouteChildren = {
  AnalizaOfferIdRoute: AnalizaOfferIdRoute,
}

const AnalizaRouteWithChildren =
  AnalizaRoute._addFileChildren(AnalizaRouteChildren)

interface ContRouteChildren {
  ContRapoarteRoute: typeof ContRapoarteRoute
  ContSetariRoute: typeof ContSetariRoute
}

const ContRouteChildren: ContRouteChildren = {
  ContRapoarteRoute: ContRapoarteRoute,
  ContSetariRoute: ContSetariRoute,
}

const ContRouteWithChildren = ContRoute._addFileChildren(ContRouteChildren)

interface RaportCompletRouteChildren {
  RaportCompletAnalysisIdRoute: typeof RaportCompletAnalysisIdRoute
}

const RaportCompletRouteChildren: RaportCompletRouteChildren = {
  RaportCompletAnalysisIdRoute: RaportCompletAnalysisIdRoute,
}

const RaportCompletRouteWithChildren = RaportCompletRoute._addFileChildren(
  RaportCompletRouteChildren,
)

interface RezultatGratuitRouteChildren {
  RezultatGratuitAnalysisIdRoute: typeof RezultatGratuitAnalysisIdRoute
}

const RezultatGratuitRouteChildren: RezultatGratuitRouteChildren = {
  RezultatGratuitAnalysisIdRoute: RezultatGratuitAnalysisIdRoute,
}

const RezultatGratuitRouteWithChildren = RezultatGratuitRoute._addFileChildren(
  RezultatGratuitRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AnalizaRoute: AnalizaRouteWithChildren,
  AutentificareRoute: AutentificareRoute,
  ContRoute: ContRouteWithChildren,
  ContactRoute: ContactRoute,
  CumFunctioneazaRoute: CumFunctioneazaRoute,
  ExempluRaportRoute: ExempluRaportRoute,
  HartaSolaraRomaniaRoute: HartaSolaraRomaniaRoute,
  IntrebariFrecventeRoute: IntrebariFrecventeRoute,
  IntroducereManualaRoute: IntroducereManualaRoute,
  RaportCompletRoute: RaportCompletRouteWithChildren,
  RecomandareSistemRoute: RecomandareSistemRoute,
  RezultatGratuitRoute: RezultatGratuitRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UploadOfertaRoute: UploadOfertaRoute,
  ApiAnalyticsRoute: ApiAnalyticsRoute,
  CorectareOfferIdRoute: CorectareOfferIdRoute,
  LegalConfidentialitateRoute: LegalConfidentialitateRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalTermeniRoute: LegalTermeniRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
